# Generated by Django 5.2.1 on 2025-05-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('studio', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('airing', 'En emisión'), ('finished', 'Finalizado'), ('upcoming', 'Próximamente')], max_length=10)),
                ('episodes', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trending', models.BooleanField(default=False)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('season', models.CharField(choices=[('winter', 'Invierno'), ('spring', 'Primavera'), ('summer', 'Verano'), ('fall', 'Otoño')], max_length=6)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_main.anime')),
            ],
            options={
                'ordering': ['-year', '-popularity'],
            },
        ),
    ]
