# Generated by Django 5.2.1 on 2025-05-19 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_main', '0002_anime_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('founded', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year', 'season']},
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='release_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('year', 'season')},
        ),
        migrations.AddField(
            model_name='anime',
            name='average_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='anime',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='anime/covers/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='duration',
            field=models.PositiveIntegerField(default=24, help_text='Duración en minutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='format',
            field=models.CharField(choices=[('tv', 'TV'), ('movie', 'Película'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Especial')], default='tv', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_main.season'),
        ),
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(upload_to='anime/posters/'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kanji', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('non-binary', 'No binario')], max_length=10)),
                ('image', models.ImageField(upload_to='characters/')),
                ('voice_actor', models.CharField(blank=True, max_length=100)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='pagina_main.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='pagina_main.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_main.studio'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['-start_date'], name='pagina_main_start_d_0a0541_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['average_score'], name='pagina_main_average_908696_idx'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='season',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='season',
            name='popularity',
        ),
    ]
