# Generated by Django 5.2.1 on 2025-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_main', '0003_genre_studio_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='anime',
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='anime',
            name='season',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='pagina_main_start_d_0a0541_idx',
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='pagina_main_average_908696_idx',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='start_date',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='trending',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='anime',
            name='format',
            field=models.CharField(choices=[('TV', 'TV'), ('Movie', 'Movie'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('Special', 'Special')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, to='pagina_main.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('airing', 'Airing'), ('finished', 'Finished'), ('upcoming', 'Upcoming')], max_length=20),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
