# Generated by Django 5.2.1 on 2025-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_main', '0005_anime_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
