# Generated by Django 5.2.1 on 2025-05-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_main', '0007_profile_useranime'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranime',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_animes', to='pagina_main.anime'),
        ),
    ]
